export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';


export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const FETCH_ACCOUNTS_FAILED = 'FETCH_ACCOUNTS_FAILED';
export const SET_SELECTED_ACCOUNT_ID = 'SET_SELECTED_ACCOUNT_ID';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const DELETE_ACCOUNT_FAILED = 'DELETE_ACCOUNT_FAILED';
export const UNSET_SELECTED_ACCOUNT_ID = 'UNSET_SELECTED_ACCOUNT_ID';

export const CREATE_ACCOUNT_START = 'CREATE_ACCOUNT_START';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAIL = 'CREATE_ACCOUNT_FAIL';

export const EDIT_ACCOUNT_START = 'EDIT_ACCOUNT_START';
export const EDIT_ACCOUNT_SUCCESS = 'EDIT_ACCOUNT_SUCCESS';
export const EDIT_ACCOUNT_FAIL = 'EDIT_ACCOUNT_FAIL';

export const SET_USERS = 'SET_USERS';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';
export const SET_SELECTED_USER_ID = 'SET_SELECTED_USER_ID';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const EDIT_USER_START = 'EDIT_USER_START';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';

export const SET_LOANS_FOR_ACCOUNT_ID = 'SET_LOANS_FOR_ACCOUNT_ID';
export const FETCH_LOANS_FAILED = 'FETCH_LOANS_FAILED';
export const SET_SELECTED_LOAN_ID = 'SET_SELECTED_LOAN_ID';
export const UNSET_SELECTED_LOAN_ID = 'UNSET_SELECTED_LOAN_ID';

export const CREATE_LOAN_START = 'CREATE_LOAN_START';
export const CREATE_LOAN_SUCCESS = 'CREATE_LOAN_SUCCESS';
export const CREATE_LOAN_FAIL = 'CREATE_LOAN_FAIL';

export const EDIT_LOAN_START = 'EDIT_LOAN_START';
export const EDIT_LOAN_SUCCESS = 'EDIT_LOAN_SUCCESS';
export const EDIT_LOAN_FAIL = 'EDIT_LOAN_FAIL';
export const DELETE_LOAN = 'DELETE_LOAN';
export const DELETE_LOAN_FAILED = 'DELETE_LOAN_FAILED';

export const SET_LOAN_INTERVALS_FOR_LOAN = 'SET_LOAN_INTERVALS_FOR_LOAN_ID';
export const FETCH_LOAN_INTERVALS_FAILED = 'FETCH_LOAN_INTERVALS_FAILED';

export const PAY_INSTALLMENT_START = 'PAY_INSTALLMENT_START';
export const PAY_INSTALLMENT_SUCCESS = 'PAY_INSTALLMENT_SUCCESS';
export const PAY_INSTALLMENT_FAIL = 'PAY_INSTALLMENT_FAIL';

export const ACCOUNT_STATEMENT_REPORT_START = 'ACCOUNT_STATEMENT_REPORT_START';
export const ACCOUNT_STATEMENT_REPORT_SUCCESS = 'ACCOUNT_STATEMENT_REPORT_SUCCESS';
export const ACCOUNT_STATEMENT_REPORT_FAIL = 'ACCOUNT_STATEMENT_REPORT_FAIL';

export const ALL_ACCOUNTS_STATEMENT_REPORT_START = 'ALL_ACCOUNTS_STATEMENT_REPORT_START';
export const ALL_ACCOUNTS_STATEMENT_REPORT_SUCCESS = 'ALL_ACCOUNTS_STATEMENT_REPORT_SUCCESS';
export const ALL_ACCOUNTS_STATEMENT_REPORT_FAIL = 'ALL_ACCOUNTS_STATEMENT_REPORT_FAIL';


export const DUES_REPORT_START = 'DUES_REPORT_START';
export const DUES_REPORT_SUCCESS = 'DUES_REPORT_SUCCESS';
export const DUES_REPORT_FAIL = 'DUES_REPORT_FAIL';

export const ALL_ACCOUNTS_DUES_REPORT_START = 'ALL_ACCOUNTS_DUES_REPORT_START';
export const ALL_ACCOUNTS_DUES_REPORT_SUCCESS = 'ALL_ACCOUNTS_DUES_REPORT_SUCCESS';
export const ALL_ACCOUNTS_DUES_REPORT_FAIL = 'ALL_ACCOUNTS_DUES_REPORT_FAIL';



export const LOANS_ISSUED_REPORT_START = 'LOANS_ISSUED_REPORT_START';
export const LOANS_ISSUED_REPORT_SUCCESS = 'LOANS_ISSUED_REPORT_SUCCESS';
export const LOANS_ISSUED_REPORT_FAIL = 'LOANS_ISSUED_REPORT_FAIL';

export const EDIT_GENERALSETTINGS_START = 'EDIT_GENERALSETTINGS_START';
export const EDIT_GENERALSETTINGS_SUCCESS = 'EDIT_GENERALSETTINGS_SUCCESS';
export const EDIT_GENERALSETTINGS_FAILED = 'EDIT_GENERALSETTINGS_FAILED';

export const EDIT_GENERAL_SETTINGS_START = 'EDIT_GENERAL_SETTINGS_START';
export const EDIT_GENERAL_SETTINGS_SUCCESS = 'EDIT_GENERAL_SETTINGS_SUCCESS';
export const EDIT_GENERAL_SETTINGS_FAILED = 'EDIT_GENERAL_SETTINGS_FAILED';
export const FETCH_GENERAL_SETTINGS_FAILED = 'FETCH_GENERAL_SETTINGS_FAILED';
export const SET_GENERAL_SETTINGS = 'SET_GENERAL_SETTINGS';
